# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: CI-Back

on:
  pull_request:
    branches: [ "Develop" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    # redis
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    # Test .yml Copy
    - name: Create TEST YML
      run: |
        cd ./src/test
        mkdir resources
        cd ./resources
        touch ./application-test.yml
        echo "${{ secrets.CMC_TEST_YML }}" > ./application-test.yml

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Build with Gradle
      run: ./gradlew clean build -x test
      shell: bash

    - name: Test with Gradle
      run: ./gradlew test


